name: flutter_taxi_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.14
  google_fonts: ^6.2.1
  fl_country_code_picker: ^0.1.9+1
  get: ^4.6.5
  pinput: ^5.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  image_picker: ^0.8.5+3
  cloud_firestore: 5.4.5
  firebase_storage: 12.3.5
  google_maps_flutter: ^2.10.0
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19
  google_api_headers: ^1.6.0
  geocoding: ^2.0.5


dependency_overrides:
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/mask.png
    - assets/mask2.png
    - assets/mask3.png
    - assets/background.png
    - assets/otpbg.png
    - assets/map_style.txt
    - assets/person.png
    - assets/dest_marker.png
    - assets/decision_background.png
    - assets/passenger_icon.png
    - assets/driver_icon.png
    - assets/mask4.png
    - assets/background.gif
    - assets/bajaj.png
    - assets/TVS.png
    - assets/mahindra.png
    - assets/prius.png
    - assets/corolla.png
    - assets/booking.png
    - assets/waiting.gif
    - assets/rating.png
    - assets/driverHome.png
    - assets/driverBooking.png
   
